version: '3'

services:
  web:
    build: .
    environment:
      dbHost: mongo:27017
    ports:
     - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${dbUsername}"
      MONGO_INITDB_ROOT_PASSWORD: "${dbPassword}"
      MONGO_INITDB_DATABASE: "${dbName}"
volumes:
  mongodata: